### PR TITLE
using power-off module.

### PR DESCRIPTION
**Pull request by hemanth**
What say?

### CODE REVIEW

**Comment by hemanth** [comment]
@kesne Actually we don't even need that `cmd`

**Comment by typicode** [comment]
Ahah, small modules FTW :+1: 
I'll merge later, thank you :)

There was also a bug with the code, as @aratramba spotted it https://github.com/typicode/stop-server/issues/3

**Comment by hemanth** [comment]
@typicode Thanks ;)

BTW, I am not using `poweroff` but `shutdown` :+1:

**Comment by typicode** [comment]
Merged :)
May have missed something as I thought it would be automatically marked as merged.

**Comment by hemanth** [comment]
Cool.

**Pull request closed without merging**
